/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visoes;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Formatter;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.*;

/**
 *
 * @author zmax
 */
public class Janela extends javax.swing.JFrame {
    private Object[] lista1;
    private Object[] lista2;
    private Object[] lista3;
    private Object voto;

        private static void escrever(Object voto) {
        File arq = new File("votos.txt");
            if (arq.exists()) {
        try {
//            arq.createNewFile();
            FileWriter fileWriter = new FileWriter(arq, true);
            try (PrintWriter printWriter = new PrintWriter(fileWriter)) {
                printWriter.println(voto.toString());
                printWriter.flush();
            }
        } catch (IOException e) {
        }
                
            } else {
                    try{
      Formatter saida = new Formatter("votos.txt");
      saida.format("_-_-CIENCIA JOVEM 2014-_-_\n"+voto.toString()+"\n");
      saida.close();
                    } catch(Exception e){
    }
            }
    }
    

    
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        voltarTela1 = new javax.swing.JButton();
        entrarTela3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        titulo3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        voltarTela2 = new javax.swing.JButton();
        entrarTela4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        titulo4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        voltarTela3 = new javax.swing.JButton();
        entrarTela5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        titulo5 = new javax.swing.JLabel();
        voltarTela4 = new javax.swing.JButton();
        entrarTela1 = new javax.swing.JButton();
        info = new javax.swing.JPanel();
        opcao = new javax.swing.JLabel();
        categorias = new javax.swing.JLabel();
        modalidade = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        trabalho = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        instituicao = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voto Popular 2.0");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(getExtendedState()|JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(20, 113, 56));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo1.setBackground(new java.awt.Color(255, 255, 255));
        titulo1.setFont(new java.awt.Font("Comic Sans MS", 1, 50)); // NOI18N
        titulo1.setForeground(new java.awt.Color(44, 66, 79));
        titulo1.setText("<html><center>Para iniciar a votação</center><center>clique em qualquer lugar da tela</center></html>");
        titulo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titulo1MouseClicked(evt);
            }
        });
        jPanel1.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 779, 210));

        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visoes/topo.png"))); // NOI18N
        logo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logo1MouseClicked(evt);
            }
        });
        jPanel1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(20, 20));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(20, 113, 56));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        titulo2.setForeground(new java.awt.Color(44, 66, 79));
        titulo2.setText("Escolha a opção de categoria");
        jPanel2.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(800, 300));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(800, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 300));

        jList1.setBackground(new java.awt.Color(251, 197, 37));
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectionBackground(new java.awt.Color(95, 152, 58));
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        voltarTela1.setBackground(new java.awt.Color(95, 152, 58));
        voltarTela1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        voltarTela1.setForeground(new java.awt.Color(44, 66, 79));
        voltarTela1.setText("Voltar");
        voltarTela1.setPreferredSize(new java.awt.Dimension(200, 140));
        voltarTela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTela1ActionPerformed(evt);
            }
        });
        jPanel2.add(voltarTela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        entrarTela3.setBackground(new java.awt.Color(95, 152, 58));
        entrarTela3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        entrarTela3.setForeground(new java.awt.Color(44, 66, 79));
        entrarTela3.setText("Continuar");
        entrarTela3.setPreferredSize(new java.awt.Dimension(200, 140));
        entrarTela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarTela3ActionPerformed(evt);
            }
        });
        jPanel2.add(entrarTela3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(20, 113, 56));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo3.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        titulo3.setForeground(new java.awt.Color(44, 66, 79));
        titulo3.setText("Escolha a categoria");
        titulo3.setToolTipText("");
        jPanel3.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setMaximumSize(new java.awt.Dimension(800, 300));
        jScrollPane2.setMinimumSize(new java.awt.Dimension(800, 300));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 300));

        jList2.setBackground(new java.awt.Color(251, 197, 37));
        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setMaximumSize(new java.awt.Dimension(0, 0));
        jList2.setMinimumSize(new java.awt.Dimension(0, 0));
        jList2.setPreferredSize(new java.awt.Dimension(0, 0));
        jList2.setSelectionBackground(new java.awt.Color(95, 152, 58));
        jScrollPane2.setViewportView(jList2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        voltarTela2.setBackground(new java.awt.Color(95, 152, 58));
        voltarTela2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        voltarTela2.setForeground(new java.awt.Color(44, 66, 79));
        voltarTela2.setText("Voltar");
        voltarTela2.setPreferredSize(new java.awt.Dimension(200, 140));
        voltarTela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTela2ActionPerformed(evt);
            }
        });
        jPanel3.add(voltarTela2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        entrarTela4.setBackground(new java.awt.Color(95, 152, 58));
        entrarTela4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        entrarTela4.setForeground(new java.awt.Color(44, 66, 79));
        entrarTela4.setText("Continuar");
        entrarTela4.setPreferredSize(new java.awt.Dimension(200, 140));
        entrarTela4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarTela4ActionPerformed(evt);
            }
        });
        jPanel3.add(entrarTela4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.setBackground(new java.awt.Color(20, 113, 56));
        jPanel4.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel4.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo4.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        titulo4.setForeground(new java.awt.Color(44, 66, 79));
        titulo4.setText("Selecione um dos trabalhos abaixo");
        jPanel4.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setMaximumSize(new java.awt.Dimension(800, 300));
        jScrollPane3.setMinimumSize(new java.awt.Dimension(800, 300));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(800, 300));

        jList3.setBackground(new java.awt.Color(251, 197, 37));
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList3.setSelectionBackground(new java.awt.Color(95, 152, 58));
        jScrollPane3.setViewportView(jList3);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        voltarTela3.setBackground(new java.awt.Color(95, 152, 58));
        voltarTela3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        voltarTela3.setForeground(new java.awt.Color(44, 66, 79));
        voltarTela3.setText("Voltar");
        voltarTela3.setPreferredSize(new java.awt.Dimension(200, 140));
        voltarTela3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTela3ActionPerformed(evt);
            }
        });
        jPanel4.add(voltarTela3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        entrarTela5.setBackground(new java.awt.Color(95, 152, 58));
        entrarTela5.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        entrarTela5.setForeground(new java.awt.Color(44, 66, 79));
        entrarTela5.setText("Continuar");
        entrarTela5.setPreferredSize(new java.awt.Dimension(200, 140));
        entrarTela5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarTela5ActionPerformed(evt);
            }
        });
        jPanel4.add(entrarTela5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(20, 113, 56));
        jPanel5.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel5.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel5.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo5.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        titulo5.setForeground(new java.awt.Color(44, 66, 79));
        titulo5.setText("Deseja votar neste trabalho?");
        jPanel5.add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        voltarTela4.setBackground(new java.awt.Color(95, 152, 58));
        voltarTela4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        voltarTela4.setForeground(new java.awt.Color(44, 66, 79));
        voltarTela4.setText("Voltar");
        voltarTela4.setPreferredSize(new java.awt.Dimension(200, 140));
        voltarTela4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTela4ActionPerformed(evt);
            }
        });
        jPanel5.add(voltarTela4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        entrarTela1.setBackground(new java.awt.Color(95, 152, 58));
        entrarTela1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        entrarTela1.setForeground(new java.awt.Color(44, 66, 79));
        entrarTela1.setText("Continuar");
        entrarTela1.setPreferredSize(new java.awt.Dimension(200, 140));
        entrarTela1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarTela1ActionPerformed(evt);
            }
        });
        jPanel5.add(entrarTela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        info.setBackground(new java.awt.Color(251, 197, 37));
        info.setMaximumSize(new java.awt.Dimension(800, 300));
        info.setMinimumSize(new java.awt.Dimension(800, 300));
        info.setPreferredSize(new java.awt.Dimension(800, 300));
        info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcao.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        opcao.setForeground(new java.awt.Color(44, 66, 79));
        opcao.setMaximumSize(new java.awt.Dimension(60, 30));
        opcao.setMinimumSize(new java.awt.Dimension(60, 30));
        opcao.setPreferredSize(new java.awt.Dimension(60, 30));
        info.add(opcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 110, -1));

        categorias.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        categorias.setForeground(new java.awt.Color(44, 66, 79));
        categorias.setMaximumSize(new java.awt.Dimension(60, 30));
        categorias.setMinimumSize(new java.awt.Dimension(60, 30));
        categorias.setPreferredSize(new java.awt.Dimension(60, 30));
        info.add(categorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 570, -1));

        modalidade.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        modalidade.setForeground(new java.awt.Color(44, 66, 79));
        modalidade.setMaximumSize(new java.awt.Dimension(60, 30));
        modalidade.setMinimumSize(new java.awt.Dimension(60, 30));
        modalidade.setPreferredSize(new java.awt.Dimension(60, 30));
        info.add(modalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 580, -1));

        estado.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        estado.setForeground(new java.awt.Color(44, 66, 79));
        estado.setPreferredSize(new java.awt.Dimension(100, 30));
        info.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 120, -1));

        jScrollPane4.setBackground(new java.awt.Color(251, 197, 37));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        trabalho.setEditable(false);
        trabalho.setBackground(new java.awt.Color(251, 197, 37));
        trabalho.setColumns(20);
        trabalho.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        trabalho.setForeground(new java.awt.Color(44, 66, 79));
        trabalho.setLineWrap(true);
        trabalho.setRows(3);
        trabalho.setWrapStyleWord(true);
        trabalho.setCaretColor(new java.awt.Color(44, 66, 79));
        trabalho.setEnabled(false);
        trabalho.setSelectedTextColor(new java.awt.Color(44, 66, 79));
        trabalho.setSelectionColor(new java.awt.Color(44, 66, 79));
        jScrollPane4.setViewportView(trabalho);

        info.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 80));

        jScrollPane5.setBackground(new java.awt.Color(251, 197, 37));
        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        instituicao.setEditable(false);
        instituicao.setBackground(new java.awt.Color(251, 197, 37));
        instituicao.setColumns(20);
        instituicao.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        instituicao.setForeground(new java.awt.Color(44, 66, 79));
        instituicao.setLineWrap(true);
        instituicao.setRows(3);
        instituicao.setWrapStyleWord(true);
        instituicao.setCaretColor(new java.awt.Color(44, 66, 79));
        instituicao.setDisabledTextColor(new java.awt.Color(44, 66, 79));
        instituicao.setEnabled(false);
        instituicao.setSelectedTextColor(new java.awt.Color(44, 66, 79));
        instituicao.setSelectionColor(new java.awt.Color(44, 66, 79));
        jScrollPane5.setViewportView(instituicao);

        info.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, 780, 80));

        jPanel5.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel6.setBackground(new java.awt.Color(20, 113, 56));
        jPanel6.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanel6.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanel6.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(95, 152, 58));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(44, 66, 79));
        jButton1.setText("Voltar");
        jButton1.setPreferredSize(new java.awt.Dimension(200, 140));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jButton2.setBackground(new java.awt.Color(95, 152, 58));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(44, 66, 79));
        jButton2.setText("Atualizar");
        jButton2.setPreferredSize(new java.awt.Dimension(200, 140));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 320, 50));

        jButton3.setBackground(new java.awt.Color(95, 152, 58));
        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(44, 66, 79));
        jButton3.setText("Continuar");
        jButton3.setPreferredSize(new java.awt.Dimension(200, 140));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel6.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 66, 79));
        jLabel1.setText("Resultado da Votação");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane6.setPreferredSize(new java.awt.Dimension(800, 300));

        jList4.setBackground(new java.awt.Color(251, 197, 37));
        jList4.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList4.setSelectionBackground(new java.awt.Color(95, 152, 58));
        jScrollPane6.setViewportView(jList4);

        jPanel6.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 500, 90, -1));
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 470, 90, -1));
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 440, 90, -1));

        jLabel6.setText("Votos 29/10/2014   -");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 440, 220, -1));

        jLabel7.setText("Votos 30/10/2014   -");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 470, 220, -1));

        jLabel8.setText("Votos 31/10/2014   -");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 220, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        lista1 = new Object[Opcoes.values().length];
        for(Opcoes o : Opcoes.values()){lista1[o.ordinal()] = o.getValor();}
        jList1.setListData(lista1);
        this.setContentPane(jPanel2);
        this.pack();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void titulo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titulo1MouseClicked
        // TODO add your handling code here:
        lista1 = new Object[Opcoes.values().length];
        for(Opcoes o : Opcoes.values()){lista1[o.ordinal()] = o.getValor();}
        jList1.setListData(lista1);
        this.setContentPane(jPanel2);
        this.pack();
    }//GEN-LAST:event_titulo1MouseClicked

    private void logo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logo1MouseClicked
        // TODO add your handling code here:
        lista1 = new Object[Opcoes.values().length];
        for(Opcoes o : Opcoes.values()){lista1[o.ordinal()] = o.getValor();}
        jList1.setListData(lista1);
        this.setContentPane(jPanel2);
        this.pack();
    }//GEN-LAST:event_logo1MouseClicked

    private void voltarTela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTela1ActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanel1);
        this.pack();
    }//GEN-LAST:event_voltarTela1ActionPerformed

    private void entrarTela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarTela3ActionPerformed
        // TODO add your handling code here:
        if (jList1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Você precisa marcar algum item para continuar.","Aviso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ArrayList temp = new ArrayList();
            for(Categorias c : Categorias.values()){
                if (jList1.getSelectedValue().toString().equals(c.getOpcao().getValor())) {
                    temp.add(c.getValor());
                }
            }
            lista2 = new Object[temp.size()];
            for(int i = 0; i < temp.size(); i++){
                lista2[i] = temp.get(i);
            }
            
            jList2.setListData(lista2);
            
            this.setContentPane(jPanel3);
            this.pack();
        }
    }//GEN-LAST:event_entrarTela3ActionPerformed

    private void voltarTela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTela2ActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanel2);
        this.pack();
    }//GEN-LAST:event_voltarTela2ActionPerformed

    private void entrarTela4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarTela4ActionPerformed
        // TODO add your handling code here:
        if (jList2.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Você precisa marcar algum item para continuar.","Aviso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            ArrayList temp = new ArrayList();
            for(Trabalhos t : Trabalhos.values()){
                if (jList2.getSelectedValue().toString().equals(t.getCategoria().getValor())) {
                    temp.add(t.getValor());
                }
            }
            lista3 = new Object[temp.size()];
            for(int i = 0; i < temp.size(); i++){
                lista3[i] = temp.get(i);
            }

            jList3.setListData(lista3);
            
            this.setContentPane(jPanel4);
            this.pack();
        }
    }//GEN-LAST:event_entrarTela4ActionPerformed

    private void voltarTela3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTela3ActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanel3);
        this.pack();
    }//GEN-LAST:event_voltarTela3ActionPerformed

    private void entrarTela5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarTela5ActionPerformed
        // TODO add your handling code here:
        if (jList3.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Você precisa marcar algum item para continuar.","Aviso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
            for(Trabalhos t : Trabalhos.values()){
                if (jList3.getSelectedValue().toString().equals(t.getValor())) {
                    
            categorias.setText(t.getCategoria().getValor().toString());
            opcao.setText(t.getCategoria().getOpcao().getValor().toString());
            modalidade.setText(t.getModalidade().getValor().toString());
            trabalho.setText(t.getValor().toString());
            instituicao.setText(t.getInstituicao().getValor().toString());
            estado.setText(t.getInstituicao().getEstado().getValor().toString());
            voto = t.name();
                    
                }
            }
            
            this.setContentPane(jPanel5);
            this.pack();
        }
    }//GEN-LAST:event_entrarTela5ActionPerformed

    private void voltarTela4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTela4ActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanel4);
        this.pack();
    }//GEN-LAST:event_voltarTela4ActionPerformed

    private void entrarTela1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarTela1ActionPerformed
        // TODO add your handling code here:
        escrever(voto);
        JOptionPane.showMessageDialog(null, "Seu voto foi realizado com sucesso!.","Parabéns!", JOptionPane.INFORMATION_MESSAGE);
        this.setContentPane(jPanel1);
        this.pack();
        
    }//GEN-LAST:event_entrarTela1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setContentPane(jPanel1);
        this.pack();        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String linha = "";
        int dia1 = 232;
        int dia2 = 384;
        int counter = 0;
        List<Voto> lista = new ArrayList<Voto>();
        for (Trabalhos t : Trabalhos.values()) {
            lista.add(new Voto(t, 0));
        }
        try {
            FileReader reader = new FileReader("votos.txt");
            BufferedReader leitor = new BufferedReader(reader);
            while (true) {
                linha = leitor.readLine();
                if (linha == null) {
                    break;
                } else {
                    for (Trabalhos t : Trabalhos.values()) {
                        if (linha.equalsIgnoreCase(t.name())) {
                                int temp = lista.get(t.ordinal()).getQuantidade();
                                lista.set(t.ordinal(), new Voto(t, temp += 1));
                                counter += 1;                            
                        }
                    }
                }
            }
        } catch (Exception e) {
        }
        Collections.sort(lista);
        jList4.setListData(lista.toArray());
        jLabel3.setText(counter-(dia1+dia2)+"");
        jLabel4.setText(dia2+"");
        jLabel5.setText(dia1+"");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:        
        this.setContentPane(jPanel6);
        this.pack();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
//        String temp = "";
        if (jList4.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Você precisa marcar algum item para continuar.","Aviso!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            
//            for(Trabalhos t : Trabalhos.values()){
//                if (jList4.getSelectedValue().toString().equalsIgnoreCase(t.getCategoria().getValor().toString())) {
//                    temp = t.getCategoria().getValor().toString();
//                }
//            }
                    JOptionPane.showMessageDialog(null,"Volte o menu e procure o trabalho nas listas." , "Informações:", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categorias;
    private javax.swing.JButton entrarTela1;
    private javax.swing.JButton entrarTela3;
    private javax.swing.JButton entrarTela4;
    private javax.swing.JButton entrarTela5;
    private javax.swing.JLabel estado;
    private javax.swing.JPanel info;
    private javax.swing.JTextArea instituicao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel modalidade;
    private javax.swing.JLabel opcao;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    private javax.swing.JLabel titulo3;
    private javax.swing.JLabel titulo4;
    private javax.swing.JLabel titulo5;
    private javax.swing.JTextArea trabalho;
    private javax.swing.JButton voltarTela1;
    private javax.swing.JButton voltarTela2;
    private javax.swing.JButton voltarTela3;
    private javax.swing.JButton voltarTela4;
    // End of variables declaration//GEN-END:variables
}
